# Generated by Django 3.0.3 on 2020-02-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('price', models.FloatField()),
            ],
        ),
    ]
